### ISSUE TITLE
Module not found: Error: Can't resolve 'pdfjs-dist' 

### ISSUE THREAD

**Issue by sureeraya** [bearnithi/bn-ng-pdf-viewer#2]
Hi,

I got the following error when try to compile project. Please help

ERROR in ./node_modules/bn-ng-pdf-viewer/fesm5/bn-ng-pdf-viewer.js
Module not found: Error: Can't resolve 'pdfjs-dist' in 'D:\u01\web\tgohrm\ng7\node_modules\bn-ng-pdf-viewer\fesm5'
ERROR in ./node_modules/bn-ng-pdf-viewer/fesm5/bn-ng-pdf-viewer.js
Module not found: Error: Can't resolve 'pdfjs-dist/build/pdf.worker' in 'D:\u01\web\tgohrm\ng7\node_modules\bn-ng-pdf-viewer\fesm5'
i ｢wdm｣: Failed to compile.

**Comment by sureeraya** [comment]
OK , I got it, just install pdfjs-dist

npm i pdfjs-dist

Thx

**Comment by narasabai** [comment]
i installed npm i pdfjs-dist
but still i am having this error
Module not found: Error: Can't resolve 'pdfjs-dist'
